language: nodejs
version: 1.0
node_js :
  - stable

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - npm run docs
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "play-cricket-client-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    edge: true
    skip_cleanup: true
    email: "chris@chris-hunt.net"
    api_key: $NPM_TOKEN
    on:
      tags: true